### ISSUE TITLE
Wrong sources for release 0.1.3 in registry

### ISSUE THREAD

**Issue by stweil** [kba/hocr-dom#2]
https://registry.npmjs.org/hocr-dom/-/hocr-dom-0.1.3.tgz does not include the changes needed to parse current Tesseract hOCR. `allowUnknownEngineSpecific` is missing.

**Comment by kba** [comment]
Thanks for spotting, seems like I published 0.1.2 again as 0.1.3. Should be fixed in hocr-dom@0.1.4 / hocrjs@0.4.0-2

**Comment by stweil** [comment]
Thank you!
